[package]
name = "collect_exact"
version = "0.1.1"
edition = "2024"

description = "Allows zero-cost collection into exact-size arrays and tuples."
repository = "https://github.com/Benjamin-Davies/collect_exact"
license = "MIT"

[dependencies]
